export const imageName = {
    appLogo : require('../assets/images/logoo.png'),
    girlOne : require('../assets/images/twoGirl.jpg'),
    girlTwo : require('../assets/images/twoGirl2.jpg'),
    girlThree : require('../assets/images/twoGirl3.jpg'),
    auto : require('../assets/images/auto.jpeg'),
    byke : require('../assets/images/byke.jpeg'),
    cab : require('../assets/images/cab.jpeg'),
    bg : require('../assets/images/bg.jpg'),
    bgDot : require('../assets/images/bg.jpg'),
    flag : require('../assets/images/flag.png'),
    pinkAuto: require('../assets/images/auto2.png'),
    pinkBike: require('../assets/images/bike2.png'),
    pinkCar: require('../assets/images/car1.png'),
    eRickShaw: require('../assets/images/e-ricksaw1.png'),
    motorByke: require('../assets/images/motor-bike1.png'),
    parcelIcon: require('../assets/images/parcel-icon.png'),
    redDot: require('../assets/images/redDot.png'),
    greenDot: require('../assets/images/greenDot.png'),
    percent: require('../assets/images/percent.png'),
    iniPoint: require('../assets/images/iniPoint.png'),
    circleSwap: require('../assets/images/circleSwap.png'),
    // girlThree : require('../assets/images/twoGirl3.jpg'),
}