

export const ScreensName = {
    splashScreen: 'splash screen',
    phoneScreen: 'phone screen',
    otpScreen: 'otp screen',
    profileScreen: 'profile screen',
    homeScreen: 'home screen',
    settingScreen: 'setting screen',
    homeStack: 'home stack',
    drawerNavigation: 'drawer navigation',
    settingStack: 'setting stack',
    emailScreen: 'email screen',
    loginScreen: 'login screen',
    welcomeScreen: 'welcome screen',
    signupScreen: 'signup screen',
    forgotPasswordScreen: 'forgot password screen',
    confirmPasswordScreen: 'confirm password screen',
    menuScreen: 'menu screen',
    takeAddressScreen: 'take address screen',
    mainMapScreen: 'main map screen',
    PaymentPage:'paymentpage',
}

export const StringData = {
    splashData: 'splash Data',
    getStarted: 'Get Started',
    whatPhoneNumber: "Hi! Welcome to Pink Rides",
    createYourAcnt: "Create your account",
    codeSentTo: "Code has been sent to +91",
    whatEmail: "What's your email?",
    didntReceiveCode: "Didn’t get OTP Code?",
    resendCode: "Resend code",
    verifCode: "Enter verification code",
    sendTo: "Send to ",
    enterPhoneNumber: "Enter your phone number to proceed",
    enterEmail: "Enter your email to proceed",
    login: 'Login',
    loginEmail: 'Login with email?',
    loginPhone: 'Login with phone?',
    signUp: 'Sign up',
    update: 'Update',
    dontAcct: "Don't have an account? ",
    allAcct: "Already have an account? ",
    email:'Email',
    fullname:'Fullname',
    password:'Password',
    passwordReq:'Password is required',
    fullnameReq:'Fullname is required',
    phone:'Phone',
    phoneReq:'Phone is required',
    otpReq:'OTP is required',
    emailReq:'Email is required',
    validEmailRequired:'Valid email is required',
    forgotPassword:'Forgot password',
    sendOtp:'Send Otp',
    save:'Save',
    next:'NEXT',
    verifyOpt:'Verify',
    verifyPhn:'Verify Phone',
    pickLocation:'Search Pickup Location',
    dropLocation:'Search Drop Location',
    bookride:'Book Ride',
    pinkBike:'Pink Bike',
    bike:'Bike',
    auto:'Auto',
    car:'Car',
    parcel:'Parcel',
    explore:'Explore',
    viewAll:'View All',
    whereGoing:'Where are you going?',
    yourCurrentLoc:'Your current location',
    fiftyRes:'Get 50% Off on First Ride',
    
}